import type { Metadata } from "next";

import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Travel With Andy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex min-h-screen">
      <Sidebar />
      <div className="flex-1 flex items-center justify-center">{children}</div>
    </main>
  );
}
